project:
  type: website

website:
  title: "example-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer: 
    left: "Copyright Info & Date" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/ 

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

